services:
  postgres:
    image: postgres:17-alpine
    container_name: kolo_postgres
    restart: always
    environment:
      POSTGRES_USER: kolo_user
      POSTGRES_PASSWORD: kolo_password
      POSTGRES_DB: kolo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
